// Import necessary components and styles
import { Inter } from "next/font/google";
import Footer from "./components/Footer";
import Header from "./components/Header";
import "./globals.css";

// Initialize the Inter font with Latin subset
// This is optimized by Next.js for performance
const inter = Inter({ subsets: ["latin"] });

// Define metadata for SEO and browser tab
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Root Layout - This is the top-level layout that wraps all pages
// It provides the basic HTML structure and common elements (Header/Footer)
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* Header appears on all pages */}
        <Header />
        {/* Page-specific content is injected here */}
        {children}
        {/* Footer appears on all pages */}
        <Footer />
      </body>
    </html>
  );
}
